SYSTEM_CASH_CATEGORY_DEFINITIONS = [
    {
        "entry_type": "CASH_IN",
        "label": "For Payables",
        "system_key": "cash_in_for_payables",
        "requires_description": False,
        "sort_order": 10,
    },
    {
        "entry_type": "CASH_IN",
        "label": "From Bank Account",
        "system_key": "cash_in_bank_transfer",
        "requires_description": False,
        "sort_order": 20,
    },
    {
        "entry_type": "CASH_IN",
        "label": "From Gcash/E-Wallet Account",
        "system_key": "cash_in_ewallet_transfer",
        "requires_description": False,
        "sort_order": 30,
    },
    {
        "entry_type": "CASH_IN",
        "label": "Others",
        "system_key": "cash_in_others",
        "requires_description": True,
        "sort_order": 40,
    },
    {
        "entry_type": "CASH_IN",
        "label": "Petty Cash",
        "system_key": "cash_in_petty_cash",
        "requires_description": False,
        "sort_order": 50,
    },
    {
        "entry_type": "CASH_OUT",
        "label": "To Gcash/E-Wallet Account (Related to shop)",
        "system_key": "cash_out_to_ewallet",
        "requires_description": False,
        "sort_order": 10,
    },
    {
        "entry_type": "CASH_OUT",
        "label": "Mechanic Payout",
        "system_key": "cash_out_mechanic_payout",
        "requires_description": False,
        "sort_order": 20,
    },
    {
        "entry_type": "CASH_OUT",
        "label": "Others (Related to shop)",
        "system_key": "cash_out_other_expenses",
        "requires_description": True,
        "sort_order": 30,
    },
    {
        "entry_type": "CASH_OUT",
        "label": "PagIbig Payment",
        "system_key": "cash_out_pagibig_payment",
        "requires_description": False,
        "sort_order": 40,
    },
    {
        "entry_type": "CASH_OUT",
        "label": "Parts Purchase",
        "system_key": "cash_out_parts_purchase",
        "requires_description": False,
        "sort_order": 50,
    },
    {
        "entry_type": "CASH_OUT",
        "label": "Philhealth Payment",
        "system_key": "cash_out_philhealth_payment",
        "requires_description": False,
        "sort_order": 60,
    },
    {
        "entry_type": "CASH_OUT",
        "label": "SSS Payment",
        "system_key": "cash_out_sss_payment",
        "requires_description": False,
        "sort_order": 70,
    },
    {
        "entry_type": "CASH_OUT",
        "label": "Staff Expense/Allowance",
        "system_key": "cash_out_staff_expense_allowance",
        "requires_description": False,
        "sort_order": 80,
    },
    {
        "entry_type": "CASH_OUT",
        "label": "Staff Salary",
        "system_key": "cash_out_staff_salary",
        "requires_description": False,
        "sort_order": 90,
    },
    {
        "entry_type": "CASH_OUT",
        "label": "Stationery/Office Supplies",
        "system_key": "cash_out_stationery_office_supplies",
        "requires_description": False,
        "sort_order": 100,
    },
    {
        "entry_type": "CASH_OUT",
        "label": "Transportation",
        "system_key": "cash_out_transportation",
        "requires_description": False,
        "sort_order": 110,
    },
    {
        "entry_type": "CASH_OUT",
        "label": "Utilities",
        "system_key": "cash_out_utilities",
        "requires_description": True,
        "sort_order": 120,
    },
]


CASH_CATEGORY_BACKFILL_ALIASES = {
    ("CASH_IN", "for payables"): "cash_in_for_payables",
    ("CASH_IN", "from bank account"): "cash_in_bank_transfer",
    ("CASH_IN", "from gcash account"): "cash_in_ewallet_transfer",
    ("CASH_IN", "from gcash/e-wallet account"): "cash_in_ewallet_transfer",
    ("CASH_IN", "from e-wallet account"): "cash_in_ewallet_transfer",
    ("CASH_IN", "others"): "cash_in_others",
    ("CASH_IN", "petty cash"): "cash_in_petty_cash",
    ("CASH_OUT", "to gcash/e-wallet account"): "cash_out_to_ewallet",
    ("CASH_OUT", "to gcash/e-wallet account (related to shop)"): "cash_out_to_ewallet",
    ("CASH_OUT", "to gcash account"): "cash_out_to_ewallet",
    ("CASH_OUT", "mechanic payout"): "cash_out_mechanic_payout",
    ("CASH_OUT", "others"): "cash_out_other_expenses",
    ("CASH_OUT", "other expenses"): "cash_out_other_expenses",
    ("CASH_OUT", "pagibig payment"): "cash_out_pagibig_payment",
    ("CASH_OUT", "parts purchase"): "cash_out_parts_purchase",
    ("CASH_OUT", "philhealth payment"): "cash_out_philhealth_payment",
    ("CASH_OUT", "sss payment"): "cash_out_sss_payment",
    ("CASH_OUT", "staff expense"): "cash_out_staff_expense_allowance",
    ("CASH_OUT", "staff expense/allowance"): "cash_out_staff_expense_allowance",
    ("CASH_OUT", "staff salary"): "cash_out_staff_salary",
    ("CASH_OUT", "stationery/office supplies"): "cash_out_stationery_office_supplies",
    ("CASH_OUT", "supplies"): "cash_out_stationery_office_supplies",
    ("CASH_OUT", "transportation"): "cash_out_transportation",
    ("CASH_OUT", "utilities"): "cash_out_utilities",
}


def normalize_cash_category_label(label):
    return " ".join(str(label or "").strip().lower().split())
